/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>JavaScript.jflex</tt>
 */
class JavascriptLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING1 = 2;
  public static final int STRING2 = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\4\1\0\1\1\1\3\22\0\1\1\1\56\1\65"+
    "\1\0\1\63\1\61\1\57\1\64\2\52\1\6\1\13\1\52\1\14"+
    "\1\7\1\5\1\10\1\17\6\22\2\11\2\52\1\53\1\54\1\55"+
    "\1\52\1\0\1\25\1\16\2\25\1\12\1\25\10\63\1\21\10\63"+
    "\1\24\2\63\1\52\1\66\1\52\1\61\1\63\1\0\1\30\1\15"+
    "\1\41\1\32\1\27\1\40\1\50\1\45\1\33\1\63\1\31\1\43"+
    "\1\51\1\34\1\20\1\37\1\63\1\26\1\42\1\35\1\47\1\44"+
    "\1\46\1\23\1\36\1\63\1\52\1\60\1\62\1\52\41\0\1\1"+
    "\u15df\0\1\1\u097f\0\13\1\35\0\2\2\5\0\1\1\57\0\1\1"+
    "\u0fa0\0\1\1\ucefe\0\1\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u0110\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\2\1\1\2\2\3\2\4\1\5\2\3\13\5"+
    "\1\1\1\5\7\3\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\11\1\13\1\14\1\0\1\2\1\0\1\4"+
    "\4\0\4\5\1\15\1\5\1\16\1\17\22\5\1\3"+
    "\1\20\1\21\1\22\1\23\1\24\3\0\1\25\1\26"+
    "\1\27\12\5\1\30\1\31\4\5\1\32\11\5\1\33"+
    "\2\5\1\0\1\34\4\5\1\35\7\5\1\36\6\5"+
    "\1\37\3\5\1\40\1\41\1\5\1\42\11\5\1\43"+
    "\1\44\3\5\1\45\1\46\1\47\1\5\1\50\1\51"+
    "\1\52\1\5\1\53\2\5\1\54\1\5\1\55\1\56"+
    "\3\5\1\57\1\60\1\5\1\61\1\5\1\62\2\5"+
    "\1\63\1\5\1\64\1\65\1\5\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339"+
    "\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1"+
    "\0\u0528\0\u055f\0\245\0\u0596\0\u05cd\0\u0604\0\u063b\0\u0672"+
    "\0\u06a9\0\245\0\245\0\245\0\u06e0\0\245\0\u0717\0\u074e"+
    "\0\u0785\0\u07bc\0\u07f3\0\245\0\u082a\0\u0861\0\u0898\0\u08cf"+
    "\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0226\0\u0a50"+
    "\0\u0a87\0\u0226\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1"+
    "\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89"+
    "\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\245\0\245\0\245"+
    "\0\245\0\245\0\u0ed3\0\u0f0a\0\u0f41\0\u08cf\0\u0906\0\u093d"+
    "\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9"+
    "\0\u1130\0\u1167\0\u0226\0\u0226\0\u119e\0\u11d5\0\u120c\0\u1243"+
    "\0\u0226\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4"+
    "\0\u13fb\0\u1432\0\u0226\0\u1469\0\u14a0\0\u14d7\0\245\0\u150e"+
    "\0\u1545\0\u157c\0\u15b3\0\u0226\0\u15ea\0\u1621\0\u1658\0\u168f"+
    "\0\u16c6\0\u16fd\0\u1734\0\u0226\0\u176b\0\u17a2\0\u17d9\0\u1810"+
    "\0\u1847\0\u187e\0\u0226\0\u18b5\0\u18ec\0\u1923\0\u0226\0\u0226"+
    "\0\u195a\0\u0226\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\u1a6d\0\u1aa4"+
    "\0\u1adb\0\u1b12\0\u1b49\0\u0226\0\u0226\0\u1b80\0\u1bb7\0\u1bee"+
    "\0\u0226\0\u0226\0\u0226\0\u1c25\0\u0226\0\u0226\0\u0226\0\u1c5c"+
    "\0\u0226\0\u1c93\0\u1cca\0\u0226\0\u1d01\0\u0226\0\u0226\0\u1d38"+
    "\0\u1d6f\0\u1da6\0\u0226\0\u0226\0\u1ddd\0\u0226\0\u1e14\0\u0226"+
    "\0\u1e4b\0\u1e82\0\u0226\0\u1eb9\0\u0226\0\u0226\0\u1ef0\0\u0226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\4\1\5\1\4\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\13\1\12\2\13"+
    "\1\12\3\13\1\17\1\20\2\13\1\21\1\22\1\23"+
    "\1\24\1\25\1\13\1\26\1\27\1\30\1\13\1\31"+
    "\1\13\1\32\3\13\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\7\1\42\1\13\1\43\1\44\1\0"+
    "\3\45\2\0\57\45\1\46\1\45\1\47\3\50\2\0"+
    "\60\50\1\46\1\51\73\0\1\4\67\0\1\52\1\53"+
    "\45\0\1\54\66\0\1\33\21\0\1\55\2\56\5\0"+
    "\1\56\2\0\1\56\53\0\1\56\2\0\1\57\2\0"+
    "\2\60\1\0\2\61\1\0\2\62\2\0\1\57\46\0"+
    "\1\56\2\12\1\57\4\0\1\12\2\0\1\12\4\0"+
    "\1\57\47\0\3\13\2\0\35\13\11\0\1\13\16\0"+
    "\1\33\40\0\1\33\26\0\1\33\37\0\1\33\22\0"+
    "\3\13\2\0\11\13\1\63\23\13\11\0\1\13\13\0"+
    "\3\13\2\0\12\13\1\64\22\13\11\0\1\13\13\0"+
    "\3\13\2\0\6\13\1\65\17\13\1\66\6\13\11\0"+
    "\1\13\13\0\3\13\2\0\3\13\1\67\6\13\1\70"+
    "\22\13\11\0\1\13\13\0\3\13\2\0\17\13\1\71"+
    "\3\13\1\72\10\13\1\73\11\0\1\13\13\0\3\13"+
    "\2\0\12\13\1\74\22\13\11\0\1\13\13\0\3\13"+
    "\2\0\11\13\1\75\7\13\1\76\6\13\1\77\4\13"+
    "\11\0\1\13\13\0\3\13\2\0\16\13\1\100\16\13"+
    "\11\0\1\13\13\0\3\13\2\0\3\13\1\101\12\13"+
    "\1\102\13\13\1\103\2\13\11\0\1\13\13\0\3\13"+
    "\2\0\3\13\1\104\7\13\1\105\12\13\1\106\6\13"+
    "\11\0\1\13\13\0\3\13\2\0\31\13\1\107\1\110"+
    "\2\13\11\0\1\13\13\0\3\13\2\0\3\13\1\111"+
    "\7\13\1\112\21\13\11\0\1\13\13\0\3\13\2\0"+
    "\16\13\1\113\11\13\1\114\4\13\11\0\1\13\56\0"+
    "\1\7\1\33\66\0\1\7\1\33\65\0\1\33\1\115"+
    "\65\0\1\7\66\0\1\33\2\0\1\33\63\0\1\33"+
    "\3\0\1\33\6\0\3\45\2\0\57\45\1\0\1\45"+
    "\27\0\1\116\5\0\1\117\1\120\26\0\1\121\2\0"+
    "\3\50\2\0\60\50\30\0\1\116\5\0\1\117\1\120"+
    "\27\0\1\122\1\0\2\52\3\0\62\52\6\123\1\124"+
    "\60\123\7\0\1\33\67\0\2\56\1\57\4\0\1\56"+
    "\2\0\1\56\4\0\1\57\47\0\2\56\1\0\2\125"+
    "\2\0\1\56\2\0\1\56\54\0\1\126\6\0\1\126"+
    "\57\0\1\127\6\0\1\127\2\0\1\127\54\0\3\130"+
    "\2\0\3\130\2\0\1\130\2\0\1\130\1\0\2\130"+
    "\1\0\1\130\5\0\2\130\35\0\3\13\2\0\12\13"+
    "\1\131\22\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\132\14\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\133\1\13\1\134\12\13\11\0\1\13\13\0\3\13"+
    "\2\0\25\13\1\135\7\13\11\0\1\13\13\0\3\13"+
    "\2\0\1\136\22\13\1\137\2\13\1\140\6\13\11\0"+
    "\1\13\13\0\3\13\2\0\25\13\1\141\7\13\11\0"+
    "\1\13\13\0\3\13\2\0\22\13\1\142\12\13\11\0"+
    "\1\13\13\0\3\13\2\0\31\13\1\143\3\13\11\0"+
    "\1\13\13\0\3\13\2\0\21\13\1\144\13\13\11\0"+
    "\1\13\13\0\3\13\2\0\22\13\1\145\12\13\11\0"+
    "\1\13\13\0\3\13\2\0\11\13\1\146\4\13\1\147"+
    "\16\13\11\0\1\13\13\0\3\13\2\0\12\13\1\150"+
    "\22\13\11\0\1\13\13\0\3\13\2\0\11\13\1\151"+
    "\23\13\11\0\1\13\13\0\3\13\2\0\17\13\1\152"+
    "\15\13\11\0\1\13\13\0\3\13\2\0\17\13\1\153"+
    "\15\13\11\0\1\13\13\0\3\13\2\0\17\13\1\154"+
    "\15\13\11\0\1\13\13\0\3\13\2\0\20\13\1\155"+
    "\4\13\1\156\7\13\11\0\1\13\13\0\3\13\2\0"+
    "\13\13\1\157\21\13\11\0\1\13\13\0\3\13\2\0"+
    "\16\13\1\160\16\13\11\0\1\13\13\0\3\13\2\0"+
    "\22\13\1\161\12\13\11\0\1\13\13\0\3\13\2\0"+
    "\16\13\1\162\16\13\11\0\1\13\13\0\3\13\2\0"+
    "\11\13\1\163\23\13\11\0\1\13\13\0\3\13\2\0"+
    "\20\13\1\164\14\13\11\0\1\13\13\0\3\13\2\0"+
    "\16\13\1\165\16\13\11\0\1\13\57\0\1\33\1\7"+
    "\11\0\6\123\1\166\60\123\5\0\1\167\1\124\70\0"+
    "\2\56\5\0\1\56\2\0\1\56\54\0\3\13\2\0"+
    "\13\13\1\170\21\13\11\0\1\13\13\0\3\13\2\0"+
    "\32\13\1\171\2\13\11\0\1\13\13\0\3\13\2\0"+
    "\12\13\1\172\22\13\11\0\1\13\13\0\3\13\2\0"+
    "\3\13\1\173\31\13\11\0\1\13\13\0\3\13\2\0"+
    "\12\13\1\174\22\13\11\0\1\13\13\0\3\13\2\0"+
    "\32\13\1\175\2\13\11\0\1\13\13\0\3\13\2\0"+
    "\13\13\1\176\21\13\11\0\1\13\13\0\3\13\2\0"+
    "\12\13\1\177\22\13\11\0\1\13\13\0\3\13\2\0"+
    "\20\13\1\200\14\13\11\0\1\13\13\0\3\13\2\0"+
    "\3\13\1\201\31\13\11\0\1\13\13\0\3\13\2\0"+
    "\12\13\1\202\22\13\11\0\1\13\13\0\3\13\2\0"+
    "\3\13\1\203\31\13\11\0\1\13\13\0\3\13\2\0"+
    "\25\13\1\204\7\13\11\0\1\13\13\0\3\13\2\0"+
    "\26\13\1\205\6\13\11\0\1\13\13\0\3\13\2\0"+
    "\13\13\1\206\21\13\11\0\1\13\13\0\3\13\2\0"+
    "\24\13\1\207\10\13\11\0\1\13\13\0\3\13\2\0"+
    "\20\13\1\210\4\13\1\211\7\13\11\0\1\13\13\0"+
    "\3\13\2\0\24\13\1\212\10\13\11\0\1\13\13\0"+
    "\3\13\2\0\12\13\1\213\22\13\11\0\1\13\13\0"+
    "\3\13\2\0\25\13\1\214\7\13\11\0\1\13\13\0"+
    "\3\13\2\0\20\13\1\215\14\13\11\0\1\13\13\0"+
    "\3\13\2\0\12\13\1\216\22\13\11\0\1\13\13\0"+
    "\3\13\2\0\15\13\1\217\17\13\11\0\1\13\13\0"+
    "\3\13\2\0\30\13\1\220\4\13\11\0\1\13\13\0"+
    "\3\13\2\0\26\13\1\221\6\13\11\0\1\13\3\0"+
    "\5\123\1\167\1\166\60\123\10\0\3\13\2\0\14\13"+
    "\1\222\20\13\11\0\1\13\13\0\3\13\2\0\11\13"+
    "\1\223\23\13\11\0\1\13\13\0\3\13\2\0\17\13"+
    "\1\224\15\13\11\0\1\13\13\0\3\13\2\0\11\13"+
    "\1\225\23\13\11\0\1\13\13\0\3\13\2\0\33\13"+
    "\1\226\1\13\11\0\1\13\13\0\3\13\2\0\32\13"+
    "\1\227\2\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\230\14\13\11\0\1\13\13\0\3\13\2\0\13\13"+
    "\1\231\21\13\11\0\1\13\13\0\3\13\2\0\11\13"+
    "\1\232\23\13\11\0\1\13\13\0\3\13\2\0\3\13"+
    "\1\233\31\13\11\0\1\13\13\0\3\13\2\0\31\13"+
    "\1\234\3\13\11\0\1\13\13\0\3\13\2\0\15\13"+
    "\1\235\17\13\11\0\1\13\13\0\3\13\2\0\26\13"+
    "\1\236\6\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\237\14\13\11\0\1\13\13\0\3\13\2\0\16\13"+
    "\1\240\16\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\241\14\13\11\0\1\13\13\0\3\13\2\0\30\13"+
    "\1\242\4\13\11\0\1\13\13\0\3\13\2\0\25\13"+
    "\1\243\7\13\11\0\1\13\13\0\3\13\2\0\24\13"+
    "\1\244\10\13\11\0\1\13\13\0\3\13\2\0\11\13"+
    "\1\245\23\13\11\0\1\13\13\0\3\13\2\0\12\13"+
    "\1\246\22\13\11\0\1\13\13\0\3\13\2\0\17\13"+
    "\1\247\15\13\11\0\1\13\13\0\3\13\2\0\15\13"+
    "\1\250\17\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\251\14\13\11\0\1\13\13\0\3\13\2\0\33\13"+
    "\1\252\1\13\11\0\1\13\13\0\3\13\2\0\26\13"+
    "\1\253\6\13\11\0\1\13\13\0\3\13\2\0\12\13"+
    "\1\254\22\13\11\0\1\13\13\0\3\13\2\0\17\13"+
    "\1\255\15\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\256\14\13\11\0\1\13\13\0\3\13\2\0\23\13"+
    "\1\257\11\13\11\0\1\13\13\0\3\13\2\0\26\13"+
    "\1\260\6\13\11\0\1\13\13\0\3\13\2\0\16\13"+
    "\1\261\16\13\11\0\1\13\13\0\3\13\2\0\17\13"+
    "\1\262\15\13\11\0\1\13\13\0\3\13\2\0\30\13"+
    "\1\263\4\13\11\0\1\13\13\0\3\13\2\0\25\13"+
    "\1\264\7\13\11\0\1\13\13\0\3\13\2\0\12\13"+
    "\1\265\22\13\11\0\1\13\13\0\3\13\2\0\20\13"+
    "\1\266\14\13\11\0\1\13\13\0\3\13\2\0\24\13"+
    "\1\267\10\13\11\0\1\13\13\0\3\13\2\0\21\13"+
    "\1\270\13\13\11\0\1\13\13\0\3\13\2\0\3\13"+
    "\1\271\31\13\11\0\1\13\13\0\3\13\2\0\32\13"+
    "\1\272\2\13\11\0\1\13\13\0\3\13\2\0\11\13"+
    "\1\273\23\13\11\0\1\13\13\0\3\13\2\0\12\13"+
    "\1\274\22\13\11\0\1\13\13\0\3\13\2\0\17\13"+
    "\1\275\15\13\11\0\1\13\13\0\3\13\2\0\12\13"+
    "\1\276\22\13\11\0\1\13\13\0\3\13\2\0\3\13"+
    "\1\277\31\13\11\0\1\13\13\0\3\13\2\0\23\13"+
    "\1\300\11\13\11\0\1\13\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7975];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\26\1\1\11\6\1\3\11\1\1\1\11"+
    "\4\1\1\0\1\11\1\0\1\1\4\0\33\1\5\11"+
    "\3\0\40\1\1\0\1\11\111\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuffer string = new StringBuffer();

	private Symbol symbol(int type){
		return new Symbol(type, yyline, yycolumn);
	}

	private Symbol symbol(int type, Object value){
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  JavascriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 222) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [116] {  }");
            { 
            }
          case 55: break;
          case 2: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [166] { return symbol(sym.DIVPUNCTUATOR, yytext()); }");
            { return symbol(sym.DIVPUNCTUATOR, yytext());
            }
          case 56: break;
          case 3: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [164] { return symbol(sym.PUNCTUATOR, yytext()); }");
            { return symbol(sym.PUNCTUATOR, yytext());
            }
          case 57: break;
          case 4: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [180] { return symbol(sym.DECIMALLITERAL, yytext()); }");
            { return symbol(sym.DECIMALLITERAL, yytext());
            }
          case 58: break;
          case 5: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [178] { return symbol(sym.IDENTIFIERNAME, yytext()); }");
            { return symbol(sym.IDENTIFIERNAME, yytext());
            }
          case 59: break;
          case 6: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [168] { return symbol(sym.RBPUNCTUATOR); }");
            { return symbol(sym.RBPUNCTUATOR);
            }
          case 60: break;
          case 7: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [185] { string.setLength(0); yybegin(STRING1); }");
            { string.setLength(0); yybegin(STRING1);
            }
          case 61: break;
          case 8: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [187] { string.setLength(0); yybegin(STRING2); }");
            { string.setLength(0); yybegin(STRING2);
            }
          case 62: break;
          case 9: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [196] { string.append( yytext() ); }");
            { string.append( yytext() );
            }
          case 63: break;
          case 10: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [193] { yybegin(YYINITIAL); "+ZZ_NL+"\t\t\t\t\t\t\t\t   return symbol(sym.STRING_LITERAL, "+ZZ_NL+"\t\t\t\t\t\t\t\t   string.toString()); }");
            { yybegin(YYINITIAL); 
								   return symbol(sym.STRING_LITERAL, 
								   string.toString());
            }
          case 64: break;
          case 11: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [202] { string.append(\'\\\\\'); }");
            { string.append('\\');
            }
          case 65: break;
          case 12: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [124] { return symbol(sym.SINGLELINECOMMENT); }");
            { return symbol(sym.SINGLELINECOMMENT);
            }
          case 66: break;
          case 13: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [129] { return symbol(sym.DO); }");
            { return symbol(sym.DO);
            }
          case 67: break;
          case 14: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [130] { return symbol(sym.IN); }");
            { return symbol(sym.IN);
            }
          case 68: break;
          case 15: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [156] { return symbol(sym.IF); }");
            { return symbol(sym.IF);
            }
          case 69: break;
          case 16: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [200] { string.append(\'\\r\'); }");
            { string.append('\r');
            }
          case 70: break;
          case 17: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [198] { string.append(\'\\n\'); }");
            { string.append('\n');
            }
          case 71: break;
          case 18: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [197] { string.append(\'\\t\'); }");
            { string.append('\t');
            }
          case 72: break;
          case 19: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [201] { string.append(\'\\\'\'); }");
            { string.append('\'');
            }
          case 73: break;
          case 20: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [214] { string.append(\'\\\"\'); }");
            { string.append('\"');
            }
          case 74: break;
          case 21: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [172] { return symbol(sym.BYNARYLITERAL, yytext()); }");
            { return symbol(sym.BYNARYLITERAL, yytext());
            }
          case 75: break;
          case 22: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [174] { return symbol(sym.OCTALLITERAL, yytext()); }");
            { return symbol(sym.OCTALLITERAL, yytext());
            }
          case 76: break;
          case 23: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [176] { return symbol(sym.HEXLITERAL, yytext()); }");
            { return symbol(sym.HEXLITERAL, yytext());
            }
          case 77: break;
          case 24: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [138] { return symbol(sym.NEW); }");
            { return symbol(sym.NEW);
            }
          case 78: break;
          case 25: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [160] { return symbol(sym.TRY); }");
            { return symbol(sym.TRY);
            }
          case 79: break;
          case 26: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [149] { return symbol(sym.FOR); }");
            { return symbol(sym.FOR);
            }
          case 80: break;
          case 27: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [135] { return symbol(sym.VAR); }");
            { return symbol(sym.VAR);
            }
          case 81: break;
          case 28: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [122] { return symbol(sym.MULTILINECOMMENT); }");
            { return symbol(sym.MULTILINECOMMENT);
            }
          case 82: break;
          case 29: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [133] { return symbol(sym.ELSE); }");
            { return symbol(sym.ELSE);
            }
          case 83: break;
          case 30: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [154] { return symbol(sym.THIS); }");
            { return symbol(sym.THIS);
            }
          case 84: break;
          case 31: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [132] { return symbol(sym.CASE); }");
            { return symbol(sym.CASE);
            }
          case 85: break;
          case 32: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [139] { return symbol(sym.VOID); }");
            { return symbol(sym.VOID);
            }
          case 86: break;
          case 33: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [147] { return symbol(sym.WITH); }");
            { return symbol(sym.WITH);
            }
          case 87: break;
          case 34: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [128] { return symbol(sym.BREAK); }");
            { return symbol(sym.BREAK);
            }
          case 88: break;
          case 35: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [157] { return symbol(sym.THROW); }");
            { return symbol(sym.THROW);
            }
          case 89: break;
          case 36: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [151] { return symbol(sym.YIELD); }");
            { return symbol(sym.YIELD);
            }
          case 90: break;
          case 37: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [144] { return symbol(sym.CONST); }");
            { return symbol(sym.CONST);
            }
          case 91: break;
          case 38: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [136] { return symbol(sym.CATCH); }");
            { return symbol(sym.CATCH);
            }
          case 92: break;
          case 39: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [140] { return symbol(sym.CLASS); }");
            { return symbol(sym.CLASS);
            }
          case 93: break;
          case 40: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [146] { return symbol(sym.SUPER); }");
            { return symbol(sym.SUPER);
            }
          case 94: break;
          case 41: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [143] { return symbol(sym.WHILE); }");
            { return symbol(sym.WHILE);
            }
          case 95: break;
          case 42: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [142] { return symbol(sym.RETURN); }");
            { return symbol(sym.RETURN);
            }
          case 96: break;
          case 43: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [137] { return symbol(sym.EXPORT); }");
            { return symbol(sym.EXPORT);
            }
          case 97: break;
          case 44: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [158] { return symbol(sym.DELETE); }");
            { return symbol(sym.DELETE);
            }
          case 98: break;
          case 45: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [159] { return symbol(sym.IMPORT); }");
            { return symbol(sym.IMPORT);
            }
          case 99: break;
          case 46: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [131] { return symbol(sym.TYPEOF); }");
            { return symbol(sym.TYPEOF);
            }
          case 100: break;
          case 47: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [150] { return symbol(sym.SWITCH); }");
            { return symbol(sym.SWITCH);
            }
          case 101: break;
          case 48: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [141] { return symbol(sym.EXTENDS); }");
            { return symbol(sym.EXTENDS);
            }
          case 102: break;
          case 49: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [155] { return symbol(sym.DEFAULT); }");
            { return symbol(sym.DEFAULT);
            }
          case 103: break;
          case 50: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [145] { return symbol(sym.FINALLY); }");
            { return symbol(sym.FINALLY);
            }
          case 104: break;
          case 51: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [152] { return symbol(sym.DEBUGGER); }");
            { return symbol(sym.DEBUGGER);
            }
          case 105: break;
          case 52: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [153] { return symbol(sym.FUNCTION); }");
            { return symbol(sym.FUNCTION);
            }
          case 106: break;
          case 53: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [148] { return symbol(sym.CONTINUE); }");
            { return symbol(sym.CONTINUE);
            }
          case 107: break;
          case 54: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [134] { return symbol(sym.INSTANCEOF); }");
            { return symbol(sym.INSTANCEOF);
            }
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java JavascriptLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        JavascriptLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new JavascriptLexer(reader);
          do {
            System.out.println(scanner.yylex());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
