


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Apr 10 11:18:01 PDT 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {

	public static final int PUNCTUATOR = 77;
  /* terminals */
	public static final int DIVPUNCTUATOR = 79;
	public static final int RBPUNCTUATOR = 81;
	public static final int DO = 44;
	public static final int IN = 45;
	public static final int IF = 71;
	public static final int NEW = 53;
	public static final int TRY = 75;
	public static final int FOR = 64;
	public static final int VAR = 50;
	public static final int ELSE = 48;
	public static final int THIS = 69;
	public static final int CASE = 47;
	public static final int VOID = 54;
	public static final int WITH = 62;
	public static final int BREAK = 43;
	public static final int THROW = 72;
	public static final int YIELD = 66;
	public static final int CATCH = 51;
	public static final int CONST = 59;
	public static final int CLASS = 55;
	public static final int SUPER = 61;
	public static final int WHILE = 58;
	public static final int RETURN = 57;
	public static final int EXPORT = 52;
	public static final int DELETE = 73;
	public static final int IMPORT = 74;
	public static final int TYPEOF = 46;
	public static final int SWITCH = 65;
	public static final int EXTENDS = 56;
	public static final int DEFAULT = 70;
	public static final int FINALLY = 60;
	public static final int DEBUGGER = 67;
	public static final int FUNCTION = 68;
	public static final int CONTINUE = 63;
	public static final int INSTANCEOF = 49;
	public static final int IDENTIFIERNAME = 87;
	public static final int DECIMALLITERAL = 144;
	public static final int OCTALLITERAL = 138;
	public static final int HEXLITERAL = 140;
	public static final int BYNARYLITERAL = 136;
	public static final int SIGNEDINTEGER = 149;
	public static final int COMMENT = 119;
	public static final int STRING_LITERAL = 172;
	public static final int REGEXLITERAL = 209;
	public static final int TEMPLATE = 184;
}

