/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;
import java.util.HashMap;
import java.util.Map;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>JavaScript.jflex</tt>
 */
class JavascriptLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING1 = 2;
  public static final int STRING2 = 4;
  public static final int COMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\106\1\107\1\4\22\0\1\1\1\37\1\64"+
    "\1\0\1\70\1\35\1\40\1\105\1\26\1\27\1\6\1\13\1\32"+
    "\1\14\1\7\1\5\1\10\1\17\6\22\2\11\1\34\1\33\1\43"+
    "\1\46\1\44\1\45\1\0\1\62\1\16\2\25\1\12\1\25\3\51"+
    "\1\63\1\51\1\51\2\51\1\21\3\51\2\51\1\61\2\51\1\24"+
    "\2\51\1\30\1\53\1\31\1\42\1\51\1\67\1\74\1\15\1\72"+
    "\1\76\1\71\1\65\1\54\1\103\1\56\1\51\1\75\1\102\1\55"+
    "\1\77\1\20\1\101\1\51\1\73\1\57\1\66\1\60\1\52\1\104"+
    "\1\23\1\100\1\51\1\47\1\41\1\50\1\36\6\0\1\106\32\0"+
    "\1\1\u15df\0\1\1\u097f\0\13\1\35\0\1\2\1\2\5\0\1\1"+
    "\57\0\1\1\u0fa0\0\1\1\ucefe\0\1\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u0110\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\2\7\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\2\3\7"+
    "\1\35\2\7\1\1\10\7\1\36\1\37\1\40\1\41"+
    "\1\37\1\40\1\2\1\0\1\42\1\43\1\0\1\44"+
    "\1\0\1\45\1\46\1\47\1\0\1\6\4\0\1\50"+
    "\1\51\1\52\1\53\1\7\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\1\71\4\7\1\72\1\73\14\7\2\0\1\74"+
    "\1\0\6\7\1\75\7\7\1\76\1\77\1\100\1\101"+
    "\1\102\1\103\1\104\1\0\1\105\1\106\1\0\1\107"+
    "\1\110\1\111\1\7\1\112\1\113\1\114\1\115\1\116"+
    "\1\7\1\117\1\120\4\7\1\121\1\7\1\122\4\7"+
    "\1\123\4\7\2\0\14\7\1\124\1\7\1\125\2\7"+
    "\12\104\1\7\1\126\1\127\7\7\1\130\2\7\1\131"+
    "\1\7\1\0\1\74\2\0\2\7\1\132\2\7\1\133"+
    "\6\7\1\134\1\7\1\135\1\7\1\136\2\7\1\137"+
    "\6\7\1\140\2\7\1\141\1\7\1\142\1\143\4\7"+
    "\1\144\1\145\1\146\1\7\1\147\1\150\2\7\1\151"+
    "\1\152\1\7\1\153\1\7\1\154\2\7\1\155\1\7"+
    "\1\156\1\7\1\157\2\7\1\160\1\7\1\161\1\162"+
    "\1\163\1\7\1\164";

  private static int [] zzUnpackAction() {
    int [] result = new int[283];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\110\0\220\0\330\0\u0120\0\u0120\0\u0168\0\u01b0"+
    "\0\u01f8\0\u0240\0\u0288\0\u02d0\0\u0318\0\u0360\0\u03a8\0\u03f0"+
    "\0\u0438\0\u0120\0\u0120\0\u0120\0\u0120\0\u0120\0\u0120\0\u0120"+
    "\0\u0480\0\u0120\0\u04c8\0\u0510\0\u0558\0\u05a0\0\u05e8\0\u0630"+
    "\0\u0120\0\u0678\0\u0120\0\u0120\0\u06c0\0\u0708\0\u0750\0\u0798"+
    "\0\u0120\0\u07e0\0\u0828\0\u0870\0\u08b8\0\u0900\0\u0948\0\u0990"+
    "\0\u09d8\0\u0a20\0\u0a68\0\u0ab0\0\u0120\0\u0af8\0\u0b40\0\u0120"+
    "\0\u0b88\0\u0bd0\0\u0c18\0\u0c60\0\u0ca8\0\u0120\0\u0cf0\0\u0c60"+
    "\0\u0d38\0\u0120\0\u0d80\0\u0120\0\u0dc8\0\u0e10\0\u0e58\0\u0ea0"+
    "\0\u0ee8\0\u0f30\0\u0120\0\u0120\0\u0120\0\u0120\0\u0f78\0\u0318"+
    "\0\u0120\0\u0fc0\0\u0120\0\u0120\0\u0120\0\u0120\0\u0120\0\u1008"+
    "\0\u0120\0\u1050\0\u0120\0\u0120\0\u1098\0\u10e0\0\u1128\0\u1170"+
    "\0\u11b8\0\u0318\0\u1200\0\u1248\0\u1290\0\u12d8\0\u1320\0\u1368"+
    "\0\u13b0\0\u13f8\0\u1440\0\u1488\0\u14d0\0\u1518\0\u1560\0\u0870"+
    "\0\u15a8\0\u0120\0\u15f0\0\u1638\0\u1680\0\u16c8\0\u1710\0\u1758"+
    "\0\u17a0\0\u0318\0\u17e8\0\u1830\0\u1878\0\u18c0\0\u1908\0\u1950"+
    "\0\u1998\0\u0120\0\u0120\0\u0120\0\u0120\0\u0120\0\u0120\0\u19e0"+
    "\0\u1a28\0\u0120\0\u0120\0\u1a70\0\u0ea0\0\u0ee8\0\u0f30\0\u1ab8"+
    "\0\u0120\0\u0120\0\u1b00\0\u0120\0\u0120\0\u1b48\0\u0318\0\u0318"+
    "\0\u1b90\0\u1bd8\0\u1c20\0\u1c68\0\u0318\0\u1cb0\0\u0318\0\u1cf8"+
    "\0\u1d40\0\u1d88\0\u1dd0\0\u0318\0\u1e18\0\u1e60\0\u1ea8\0\u1ef0"+
    "\0\u1f38\0\u1f80\0\u1fc8\0\u2010\0\u2058\0\u20a0\0\u20e8\0\u2130"+
    "\0\u2178\0\u21c0\0\u2208\0\u2250\0\u2298\0\u22e0\0\u0318\0\u2328"+
    "\0\u0318\0\u2370\0\u23b8\0\u2400\0\u2448\0\u2490\0\u24d8\0\u2520"+
    "\0\u2568\0\u25b0\0\u25f8\0\u2640\0\u0120\0\u2688\0\u0120\0\u0318"+
    "\0\u26d0\0\u2718\0\u2760\0\u27a8\0\u27f0\0\u2838\0\u2880\0\u0318"+
    "\0\u28c8\0\u2910\0\u0318\0\u2958\0\u29a0\0\u0870\0\u29e8\0\u2a30"+
    "\0\u2a78\0\u2ac0\0\u0318\0\u2b08\0\u2b50\0\u0318\0\u2b98\0\u2be0"+
    "\0\u2c28\0\u2c70\0\u2cb8\0\u2d00\0\u0318\0\u2d48\0\u0318\0\u2d90"+
    "\0\u0318\0\u2dd8\0\u2e20\0\u0318\0\u2e68\0\u2eb0\0\u2ef8\0\u2f40"+
    "\0\u2f88\0\u2fd0\0\u0318\0\u3018\0\u3060\0\u0318\0\u30a8\0\u0318"+
    "\0\u0318\0\u30f0\0\u3138\0\u3180\0\u31c8\0\u0318\0\u0318\0\u0318"+
    "\0\u3210\0\u0318\0\u0318\0\u3258\0\u32a0\0\u0318\0\u0318\0\u32e8"+
    "\0\u0318\0\u3330\0\u0318\0\u3378\0\u33c0\0\u0318\0\u3408\0\u0318"+
    "\0\u3450\0\u0318\0\u3498\0\u34e0\0\u0318\0\u3528\0\u0318\0\u0318"+
    "\0\u0318\0\u3570\0\u0318";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[283];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\3\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\15\1\14\1\21\1\15"+
    "\1\14\3\15\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\15\1\45\1\5"+
    "\1\46\1\15\1\47\1\50\4\15\1\51\1\52\1\53"+
    "\1\54\1\15\1\55\1\56\1\57\2\15\1\60\1\61"+
    "\1\62\1\15\1\63\1\15\1\64\1\65\1\5\1\6"+
    "\3\66\2\6\46\66\1\67\31\66\1\70\2\66\3\71"+
    "\2\6\46\71\1\72\10\71\1\70\23\71\2\6\1\5"+
    "\3\6\1\73\77\6\2\5\113\0\1\6\104\0\2\74"+
    "\3\0\1\75\1\76\21\74\1\77\1\0\14\74\1\100"+
    "\4\74\1\101\34\74\5\0\1\102\1\103\37\0\1\104"+
    "\50\0\1\105\2\106\5\0\1\106\2\0\1\106\74\0"+
    "\1\106\2\0\1\107\2\0\2\110\1\0\2\111\1\0"+
    "\2\112\44\0\1\107\25\0\1\106\2\14\1\107\4\0"+
    "\1\14\2\0\1\14\46\0\1\107\26\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\10\15\1\0\2\15\1\0"+
    "\15\15\16\0\1\113\32\0\1\114\55\0\1\115\31\0"+
    "\1\116\51\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\2\15\1\0\3\15\1\117\11\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\1\120\1\15\1\0\15\15\51\0\1\121\107\0\1\122"+
    "\101\0\1\123\5\0\1\124\102\0\1\125\4\0\1\126"+
    "\107\0\1\127\104\0\1\130\2\0\1\131\105\0\1\132"+
    "\1\0\1\133\105\0\1\134\1\0\1\135\51\0\3\15"+
    "\2\0\3\15\1\136\5\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\4\15\1\137\10\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\1\15\1\140\13\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\1\15\1\141\6\15\1\0\1\142"+
    "\1\15\1\0\7\15\1\143\5\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\4\15\1\144\3\15\1\0"+
    "\1\15\1\145\1\0\1\15\1\146\12\15\1\147\13\0"+
    "\3\15\2\0\3\15\1\150\5\15\23\0\2\15\1\0"+
    "\2\15\1\151\1\15\1\152\3\15\1\0\2\15\1\0"+
    "\4\15\1\153\10\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\3\15\1\154"+
    "\1\155\3\15\1\156\2\15\1\157\1\15\3\0\53\160"+
    "\1\161\13\160\1\162\1\163\17\160\10\0\3\15\2\0"+
    "\6\15\1\164\2\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\12\15\1\165\2\15\13\0\3\15\2\0"+
    "\3\15\1\166\5\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\4\15\1\167\5\15\1\170\2\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\1\15\1\171\13\15\13\0\3\15\2\0"+
    "\3\15\1\172\5\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\1\15\1\173\13\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\4\15\1\174\3\15\1\0"+
    "\2\15\1\0\1\15\1\175\13\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\2\15\1\176\5\15\1\0"+
    "\2\15\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\1\15\1\177"+
    "\13\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\2\15\1\200\5\15\1\0\2\15\1\0\13\15\1\201"+
    "\1\15\3\0\3\66\2\0\46\66\1\0\31\66\1\0"+
    "\2\66\66\0\1\202\4\0\1\203\3\0\1\204\5\0"+
    "\1\205\2\0\3\71\2\0\46\71\1\0\10\71\1\0"+
    "\23\71\64\0\1\206\1\0\1\202\4\0\1\203\3\0"+
    "\1\204\15\0\1\207\102\0\2\74\3\0\1\210\22\74"+
    "\1\77\1\0\21\74\1\101\34\74\2\75\3\0\103\75"+
    "\2\77\3\0\23\77\1\0\1\74\21\77\1\211\34\77"+
    "\2\74\3\0\103\74\46\0\1\212\50\0\1\213\110\0"+
    "\2\106\1\107\4\0\1\106\2\0\1\106\46\0\1\107"+
    "\26\0\2\106\1\0\2\214\2\0\1\106\2\0\1\106"+
    "\75\0\1\215\6\0\1\215\100\0\1\216\6\0\1\216"+
    "\2\0\1\216\75\0\3\217\2\0\3\217\2\0\1\217"+
    "\2\0\1\217\34\0\1\217\2\0\1\217\3\0\2\217"+
    "\1\0\1\217\1\0\1\217\21\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\1\15"+
    "\1\220\13\15\51\0\1\221\107\0\1\222\105\0\1\223"+
    "\1\0\1\224\107\0\1\225\51\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\2\15\1\226\5\15\1\0\2\15"+
    "\1\0\15\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\3\15\1\227\11\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\1\15\1\230\1\0\15\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\10\15\1\0\2\15\1\0"+
    "\11\15\1\231\3\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\3\15\1\232\4\15\1\0\2\15\1\0"+
    "\15\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\2\15\1\0\11\15\1\233\3\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\4\15\1\234\10\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\10\15\1\0\1\15\1\235"+
    "\1\0\15\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\2\15\1\236\5\15\1\0\2\15\1\0\15\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\3\15\1\237\11\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\7\15\1\240\5\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\7\15"+
    "\1\241\5\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\12\15\1\242\2\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\4\15"+
    "\1\243\3\15\1\0\2\15\1\0\10\15\1\244\4\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\3\15\1\245\11\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\11\15\1\246\3\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\2\15\1\247\5\15\1\0\2\15"+
    "\1\0\3\15\1\250\11\15\3\0\2\160\3\0\3\160"+
    "\1\251\12\160\1\252\133\160\1\162\40\160\10\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\1\15"+
    "\1\253\1\0\11\15\1\254\3\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\3\15\1\255\4\15\1\0"+
    "\2\15\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\7\15\1\256"+
    "\5\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\3\15\1\257\4\15\1\0\1\15\1\260\1\0\15\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\4\15\1\261\10\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\1\15"+
    "\1\262\1\0\15\15\13\0\3\15\2\0\1\263\10\15"+
    "\23\0\2\15\1\0\10\15\1\0\1\264\1\15\1\0"+
    "\12\15\1\265\2\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\12\15\1\266"+
    "\2\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\2\15\1\0\14\15\1\267\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\1\15\1\270\13\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\1\15\1\271\1\0"+
    "\15\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\1\15\1\272\1\0\15\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\2\15\1\273\5\15"+
    "\1\0\2\15\1\0\15\15\26\0\1\274\1\275\27\0"+
    "\1\276\1\277\1\300\1\301\1\302\1\303\1\304\1\305"+
    "\24\0\2\77\3\0\103\77\10\0\2\106\5\0\1\106"+
    "\2\0\1\106\75\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\4\15\1\306\10\15"+
    "\51\0\1\307\51\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\6\15\1\310\6\15"+
    "\13\0\3\15\2\0\3\15\1\311\5\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\15\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\1\15"+
    "\1\312\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\1\15\1\313"+
    "\13\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\1\15\1\314\1\0\15\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\1\15"+
    "\1\315\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\4\15\1\316"+
    "\10\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\2\15\1\0\2\15\1\317\12\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\3\15\1\243"+
    "\4\15\1\0\2\15\1\0\15\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\10\15\1\0\2\15\1\0"+
    "\1\15\1\320\13\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\1\321\7\15\1\0\2\15\1\0\15\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\1\15\1\322\13\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\3\15\1\323\4\15"+
    "\1\0\2\15\1\0\15\15\13\0\3\15\2\0\3\15"+
    "\1\324\5\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\15\15\3\0\53\160\1\325\13\160\1\326\1\327"+
    "\17\160\10\0\3\330\2\0\3\330\2\0\1\330\2\0"+
    "\1\330\34\0\1\330\2\0\1\330\3\0\2\330\1\0"+
    "\1\330\1\0\1\330\21\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\1\15\1\331"+
    "\13\15\13\0\3\15\2\0\3\15\1\332\5\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\15\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\1\15\1\333\13\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\3\15\1\334\4\15\1\0"+
    "\1\15\1\335\1\0\15\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\1\15"+
    "\1\336\13\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\2\15\1\337\12\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\3\15"+
    "\1\340\4\15\1\0\2\15\1\0\15\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\4\15\1\341\3\15"+
    "\1\0\2\15\1\0\15\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\4\15\1\342\3\15\1\0\2\15"+
    "\1\0\15\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\4\15\1\343\10\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\1\15\1\344\13\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\12\15\1\345\2\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\12\15"+
    "\1\346\2\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\13\15\1\347\1\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\12\15\1\350\2\15\27\0\1\275"+
    "\32\0\1\301\1\302\1\303\1\304\1\305\103\0\1\301"+
    "\1\302\1\303\1\304\1\305\47\0\1\274\1\275\30\0"+
    "\1\277\1\300\1\301\1\302\1\303\1\304\1\305\47\0"+
    "\1\274\1\275\31\0\1\300\1\301\1\302\1\303\1\304"+
    "\1\305\47\0\1\274\1\275\32\0\1\301\1\302\1\303"+
    "\1\304\1\305\104\0\1\302\1\303\1\304\1\305\105\0"+
    "\1\303\1\304\1\305\106\0\1\304\1\305\107\0\1\305"+
    "\34\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\5\15\1\351\7\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\3\15\1\352\11\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\4\15"+
    "\1\353\10\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\3\15\1\354\11\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\2\15"+
    "\1\355\5\15\1\0\2\15\1\0\15\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\2\15\1\356\12\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\12\15"+
    "\1\357\2\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\1\15\1\360\1\0\15\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\1\15\1\361\13\15\13\0\3\15\2\0"+
    "\3\15\1\362\5\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\14\15\1\363"+
    "\3\0\10\160\1\251\42\160\1\325\13\160\1\326\1\327"+
    "\66\160\1\326\3\160\1\325\13\160\1\326\1\327\17\160"+
    "\10\0\3\160\2\0\3\160\2\0\1\160\2\0\1\160"+
    "\34\0\1\160\2\0\1\160\3\0\2\160\1\0\1\160"+
    "\1\0\1\160\21\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\7\15\1\364\5\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\3\15\1\365\11\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\1\15"+
    "\1\366\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\2\15\1\367\5\15\1\0\2\15\1\0"+
    "\15\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\2\15\1\0\13\15\1\370\1\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\3\15\1\371"+
    "\4\15\1\0\2\15\1\0\15\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\10\15\1\0\2\15\1\0"+
    "\3\15\1\372\11\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\1\373\7\15\1\0\2\15\1\0\15\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\4\15"+
    "\1\374\3\15\1\0\2\15\1\0\15\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\1\15"+
    "\1\375\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\6\15\1\376"+
    "\6\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\2\15\1\0\1\15\1\377\13\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\1\15\1\u0100\1\0\15\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\7\15"+
    "\1\u0101\5\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\2\15\1\u0102\12\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\13\15\1\u0103\1\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\12\15\1\u0104\2\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\2\15\1\u0105\5\15\1\0\2\15"+
    "\1\0\15\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\1\15\1\u0106\1\0\15\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\1\u0107\1\15\1\0\15\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\6\15"+
    "\1\u0108\6\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\1\15\1\u0109\1\0\15\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\7\15\1\u010a\5\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\10\15\1\0\2\15\1\0"+
    "\7\15\1\u010b\5\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\1\u010c\7\15\1\0\2\15\1\0\15\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\2\15\1\0\12\15\1\u010d\2\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\10\15\1\0\2\15"+
    "\1\0\1\15\1\u010e\13\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\10\15\1\0\2\15\1\0\2\15"+
    "\1\u010f\12\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\10\15\1\u0110\4\15"+
    "\13\0\3\15\2\0\3\15\1\u0111\5\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\15\15\13\0\3\15"+
    "\2\0\11\15\23\0\2\15\1\0\3\15\1\u0112\4\15"+
    "\1\0\2\15\1\0\15\15\13\0\3\15\2\0\11\15"+
    "\23\0\2\15\1\0\4\15\1\u0113\3\15\1\0\2\15"+
    "\1\0\15\15\13\0\3\15\2\0\11\15\23\0\2\15"+
    "\1\0\10\15\1\0\2\15\1\0\1\15\1\u0114\13\15"+
    "\13\0\3\15\2\0\11\15\23\0\2\15\1\0\10\15"+
    "\1\0\1\15\1\u0115\1\0\15\15\13\0\3\15\2\0"+
    "\11\15\23\0\2\15\1\0\10\15\1\0\2\15\1\0"+
    "\1\15\1\u0116\13\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\2\15\1\0\7\15\1\u0117"+
    "\5\15\13\0\3\15\2\0\11\15\23\0\2\15\1\0"+
    "\10\15\1\0\2\15\1\0\1\15\1\u0118\13\15\13\0"+
    "\3\15\2\0\11\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\3\15\1\u0119\11\15\13\0\3\15\2\0"+
    "\3\15\1\u011a\5\15\23\0\2\15\1\0\10\15\1\0"+
    "\2\15\1\0\15\15\13\0\3\15\2\0\11\15\23\0"+
    "\2\15\1\0\10\15\1\0\1\u011b\1\15\1\0\15\15"+
    "\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[13752];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\13\1\7\11\1\1\1\11\6\1\1\11"+
    "\1\1\2\11\4\1\1\11\13\1\1\11\2\1\1\11"+
    "\3\1\1\0\1\1\1\11\1\0\1\1\1\0\1\11"+
    "\1\1\1\11\1\0\1\1\4\0\4\11\2\1\1\11"+
    "\1\1\5\11\1\1\1\11\1\1\2\11\23\1\2\0"+
    "\1\11\1\0\16\1\6\11\1\1\1\0\2\11\1\0"+
    "\4\1\2\11\1\1\2\11\23\1\2\0\32\1\1\11"+
    "\1\1\1\11\15\1\1\0\1\1\2\0\103\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[283];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuffer string = new StringBuffer();
	
	public HashMap<String,Integer> table = new HashMap<String,Integer>();
	
    public String getIdName(int idval){
        for (Map.Entry<String, Integer> e : table.entrySet()) {
            int value = e.getValue();
            if (value == idval)
                return e.getKey();
        }
        return "";
    }
    
	int lastKey = 0;

	private Symbol symbol(int type){
		return new Symbol(type, yyline, yycolumn);
	}

	private Symbol symbol(int type, Object value){
		return new Symbol(type, yyline, yycolumn, value);
	}
	
    public int curr_lineno(){
        return yyline;
    }
     public int curr_colno(){
        return yycolumn;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  JavascriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 246) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case STRING1: {
              return symbol(sym.ERROR_B,"EOF in string constant on line "+(yyline+1));
            }
            case 284: break;
            case STRING2: {
              return symbol(sym.ERROR_B,"EOF in string constant on line "+(yyline+1));
            }
            case 285: break;
            case COMMENT: {
              return symbol(sym.ERROR_B,"EOF in comment on line "+(yyline+1));
            }
            case 286: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return symbol(sym.ERROR,"Illegal character <"+
													yytext()+"> at row "+(yyline+1)+" column "+(yycolumn+1));
            }
          case 117: break;
          case 2: 
            { 
            }
          case 118: break;
          case 3: 
            { return symbol(sym.DIV);
            }
          case 119: break;
          case 4: 
            { return symbol(sym.STAR);
            }
          case 120: break;
          case 5: 
            { return symbol(sym.DOT);
            }
          case 121: break;
          case 6: 
            { return symbol(sym.DECIMALLITERAL, yytext());
            }
          case 122: break;
          case 7: 
            { if(table.containsKey(yytext())){
										return symbol(sym.IDENTIFIERNAME, table.get(yytext()));
									}
									else{
										table.put(yytext(),lastKey);
										lastKey++;
										return symbol(sym.IDENTIFIERNAME, lastKey-1);
									}
            }
          case 123: break;
          case 8: 
            { return symbol(sym.PLUS);
            }
          case 124: break;
          case 9: 
            { return symbol(sym.MINUS);
            }
          case 125: break;
          case 10: 
            { return symbol(sym.LPAR);
            }
          case 126: break;
          case 11: 
            { return symbol(sym.RPAR);
            }
          case 127: break;
          case 12: 
            { return symbol(sym.LSQPAR);
            }
          case 128: break;
          case 13: 
            { return symbol(sym.RSQPAR);
            }
          case 129: break;
          case 14: 
            { return symbol(sym.COMMA);
            }
          case 130: break;
          case 15: 
            { return symbol(sym.SEMI);
            }
          case 131: break;
          case 16: 
            { return symbol(sym.COLON);
            }
          case 132: break;
          case 17: 
            { return symbol(sym.MOD);
            }
          case 133: break;
          case 18: 
            { return symbol(sym.TILDE);
            }
          case 134: break;
          case 19: 
            { return symbol(sym.NOT);
            }
          case 135: break;
          case 20: 
            { return symbol(sym.AND);
            }
          case 136: break;
          case 21: 
            { return symbol(sym.OR);
            }
          case 137: break;
          case 22: 
            { return symbol(sym.HAT);
            }
          case 138: break;
          case 23: 
            { return symbol(sym.LT);
            }
          case 139: break;
          case 24: 
            { return symbol(sym.GT);
            }
          case 140: break;
          case 25: 
            { return symbol(sym.QUESTION);
            }
          case 141: break;
          case 26: 
            { return symbol(sym.ASSIGN);
            }
          case 142: break;
          case 27: 
            { return symbol(sym.LBPAR);
            }
          case 143: break;
          case 28: 
            { return symbol(sym.RBPAR);
            }
          case 144: break;
          case 29: 
            { string.setLength(0); yybegin(STRING2);
            }
          case 145: break;
          case 30: 
            { string.setLength(0); yybegin(STRING1);
            }
          case 146: break;
          case 31: 
            { string.append( yytext() );
            }
          case 147: break;
          case 32: 
            { string.append('\\');
            }
          case 148: break;
          case 33: 
            { yybegin(YYINITIAL); 
								   return symbol(sym.STRING_LITERAL, 
								   string.toString());
            }
          case 149: break;
          case 34: 
            { return symbol(sym.COMMENT);
            }
          case 150: break;
          case 35: 
            { yybegin(COMMENT);
            }
          case 151: break;
          case 36: 
            { return symbol(sym.DIVEQ);
            }
          case 152: break;
          case 37: 
            { return symbol(sym.ERROR_B, "Unmatched */ on line "+(yyline+1));
            }
          case 153: break;
          case 38: 
            { return symbol(sym.DSTAR);
            }
          case 154: break;
          case 39: 
            { return symbol(sym.STAREQ);
            }
          case 155: break;
          case 40: 
            { return symbol(sym.DPLUS);
            }
          case 156: break;
          case 41: 
            { return symbol(sym.PLUSEQ);
            }
          case 157: break;
          case 42: 
            { return symbol(sym.DMINUS);
            }
          case 158: break;
          case 43: 
            { return symbol(sym.MINUSEQ);
            }
          case 159: break;
          case 44: 
            { return symbol(sym.OF);
            }
          case 160: break;
          case 45: 
            { return symbol(sym.MODEQ);
            }
          case 161: break;
          case 46: 
            { return symbol(sym.NEQ);
            }
          case 162: break;
          case 47: 
            { return symbol(sym.LOGAND);
            }
          case 163: break;
          case 48: 
            { return symbol(sym.ANDEQ);
            }
          case 164: break;
          case 49: 
            { return symbol(sym.LOGOR);
            }
          case 165: break;
          case 50: 
            { return symbol(sym.OREQ);
            }
          case 166: break;
          case 51: 
            { return symbol(sym.HATEQ);
            }
          case 167: break;
          case 52: 
            { return symbol(sym.TWOLANG);
            }
          case 168: break;
          case 53: 
            { return symbol(sym.LEQ);
            }
          case 169: break;
          case 54: 
            { return symbol(sym.TWORANG);
            }
          case 170: break;
          case 55: 
            { return symbol(sym.GEQ);
            }
          case 171: break;
          case 56: 
            { return symbol(sym.ARROW);
            }
          case 172: break;
          case 57: 
            { return symbol(sym.EQ);
            }
          case 173: break;
          case 58: 
            { return symbol(sym.IF);
            }
          case 174: break;
          case 59: 
            { return symbol(sym.IN);
            }
          case 175: break;
          case 60: 
            { return symbol(sym.TEMPLATE, yytext());
            }
          case 176: break;
          case 61: 
            { return symbol(sym.DO);
            }
          case 177: break;
          case 62: 
            { string.append('\t');
            }
          case 178: break;
          case 63: 
            { string.append('\r');
            }
          case 179: break;
          case 64: 
            { string.append('\n');
            }
          case 180: break;
          case 65: 
            { string.append('\'');
            }
          case 181: break;
          case 66: 
            { string.append('\"');
            }
          case 182: break;
          case 67: 
            { yybegin(YYINITIAL);
            }
          case 183: break;
          case 68: 
            { return symbol(sym.REGEXLITERAL, yytext());
            }
          case 184: break;
          case 69: 
            { return symbol(sym.TWOSTAREQ);
            }
          case 185: break;
          case 70: 
            { return symbol(sym.DOT3);
            }
          case 186: break;
          case 71: 
            { return symbol(sym.BYNARYLITERAL, yytext());
            }
          case 187: break;
          case 72: 
            { return symbol(sym.OCTALLITERAL, yytext());
            }
          case 188: break;
          case 73: 
            { return symbol(sym.HEXLITERAL, yytext());
            }
          case 189: break;
          case 74: 
            { return symbol(sym.TYPENEQ);
            }
          case 190: break;
          case 75: 
            { return symbol(sym.TWOLANGEQ);
            }
          case 191: break;
          case 76: 
            { return symbol(sym.THREERANG);
            }
          case 192: break;
          case 77: 
            { return symbol(sym.TWORANGEQ);
            }
          case 193: break;
          case 78: 
            { return symbol(sym.TYPEEQ);
            }
          case 194: break;
          case 79: 
            { return symbol(sym.VAR);
            }
          case 195: break;
          case 80: 
            { return symbol(sym.GET);
            }
          case 196: break;
          case 81: 
            { return symbol(sym.SET);
            }
          case 197: break;
          case 82: 
            { return symbol(sym.FOR);
            }
          case 198: break;
          case 83: 
            { return symbol(sym.TRY);
            }
          case 199: break;
          case 84: 
            { return symbol(sym.NEW);
            }
          case 200: break;
          case 85: 
            { return symbol(sym.LET);
            }
          case 201: break;
          case 86: 
            { return symbol(sym.THREERANGEQ);
            }
          case 202: break;
          case 87: 
            { return symbol(sym.VOID);
            }
          case 203: break;
          case 88: 
            { return symbol (sym.BOOLEANLITERAL, yytext());
            }
          case 204: break;
          case 89: 
            { return symbol(sym.THIS);
            }
          case 205: break;
          case 90: 
            { return symbol(sym.ELSE);
            }
          case 206: break;
          case 91: 
            { return symbol(sym.CASE);
            }
          case 207: break;
          case 92: 
            { return symbol(sym.NULL);
            }
          case 208: break;
          case 93: 
            { return symbol(sym.WITH);
            }
          case 209: break;
          case 94: 
            { return symbol(sym.BREAK);
            }
          case 210: break;
          case 95: 
            { return symbol(sym.SUPER);
            }
          case 211: break;
          case 96: 
            { return symbol(sym.THROW);
            }
          case 212: break;
          case 97: 
            { return symbol(sym.CONST);
            }
          case 213: break;
          case 98: 
            { return symbol(sym.CATCH);
            }
          case 214: break;
          case 99: 
            { return symbol(sym.CLASS);
            }
          case 215: break;
          case 100: 
            { return symbol(sym.YIELD);
            }
          case 216: break;
          case 101: 
            { return symbol(sym.WHILE);
            }
          case 217: break;
          case 102: 
            { return symbol(sym.IMPORT);
            }
          case 218: break;
          case 103: 
            { return symbol(sym.STATIC);
            }
          case 219: break;
          case 104: 
            { return symbol(sym.SWITCH);
            }
          case 220: break;
          case 105: 
            { return symbol(sym.TARGET);
            }
          case 221: break;
          case 106: 
            { return symbol(sym.TYPEOF);
            }
          case 222: break;
          case 107: 
            { return symbol(sym.EXPORT);
            }
          case 223: break;
          case 108: 
            { return symbol(sym.RETURN);
            }
          case 224: break;
          case 109: 
            { return symbol(sym.DELETE);
            }
          case 225: break;
          case 110: 
            { return symbol(sym.FINALLY);
            }
          case 226: break;
          case 111: 
            { return symbol(sym.EXTENDS);
            }
          case 227: break;
          case 112: 
            { return symbol(sym.DEFAULT);
            }
          case 228: break;
          case 113: 
            { return symbol(sym.FUNCTION);
            }
          case 229: break;
          case 114: 
            { return symbol(sym.CONTINUE);
            }
          case 230: break;
          case 115: 
            { return symbol(sym.DEBUGGER);
            }
          case 231: break;
          case 116: 
            { return symbol(sym.INSTANCEOF);
            }
          case 232: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
